### ISSUE TITLE
Issues with accents and special characters

### ISSUE THREAD

**Issue by marc-vage** [orcema/node-red-google-notify#2]
I tried to play the string "bé" using "catalan" language and it raises an error "check media server on config". 
If I remove the accent and send the string "be" it works well.

It seems there is an issue managing non-english characters.

I checked in the TMP folder and the audio MP3 is saved ok, so the issue is when sending this MP3 to the google home

**Comment by orcema** [comment]
hello,

I tried the "bé" using "catalna" and it works for me.
What version have you installed ? On what device ? Can you please share the log details ?

**Comment by marc-vage** [comment]
I am using the latest version (installed today), and casting to a google home mini
I am now trying to get the log file for you and I cannot reproduce the issue again  :-(   It's now working well. I do not understand. Forget then the issue.
Thank you for your fast support!

**Comment by marc-vage** [comment]
Cannot reproduce it anymore. I close the ticket. Thank you
