### ISSUE TITLE
Feature request: text from inject node or flow to TTS output 

### ISSUE THREAD

**Issue by olderbag** [orcema/node-red-google-notify#3]
I would like to see the following feature:
If field "Text" is left blank, the TTS output is any text, that comes from the inject node or is generated within the flow.

Would be great to (e.g.) hear debug infos, error messages...

**Comment by orcema** [comment]
[status updated as pending for implementation](https://github.com/orcema/node-red-google-notify/projects)

**Comment by orcema** [comment]
if msg object is missing a "playMessage" and the node is missing default text (see figure below)

<img width="489" alt="Screenshot 2021-11-19 at 20 00 48" src="https://user-images.githubusercontent.com/12600222/142677424-9fe1ea08-c7fe-444c-a1e6-9ef5498d137d.png">

then the **payload** of the message will be considered as a text message starting from version: "1.4.7"

You can get debug infos if you set the debug output to "complete msg object" (see figure below)

<img width="500" alt="Screenshot 2021-11-19 at 19 59 39" src="https://user-images.githubusercontent.com/12600222/142677731-9f75d9f5-fd3e-4c48-ade2-9f2205c5c723.png">

and then you will get something like this

<img width="297" alt="Screenshot 2021-11-19 at 19 57 02" src="https://user-images.githubusercontent.com/12600222/142677804-147ba4a9-54ec-4d59-8ba7-3ae9b3e00ff1.png">

**Comment by orcema** [comment]
version 1.4.7 is published
