### ISSUE TITLE
Error during command line install attempt

### ISSUE THREAD

**Issue by ger19wmu** [orcema/node-red-google-notify#4]
Getting an error during install from command line.  When I run 
`npm install node-red-google-notify`

The install errors out with:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/orcema/file-server.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

I will fully admit I'm still fairly new to a lot of node-red and linux in general...but following my nose around points to the file-server being a dependency, I believe...but it also appears that the error is happening when it tries to install that dependency for me as the log has this in it:

16 silly resolveWithNewModule node-red-google-notify@1.4.7 checking installable status
17 silly fetchPackageMetaData error for file-server@git://github.com/orcema/file-server.git Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t git://github.com/orcema/file-server.git
17 silly fetchPackageMetaData

Anyone able to offer some help/suggestions?  I would greatly appreciate it!

Thanks!

**Comment by orcema** [comment]
Hi,
Do you use node-red as stand-alone or as home assistant add-on ?

I tried right now a command line install and it worked for me, so i guess there must be some connexion issues on your side 

<img width="1567" alt="Screenshot 2021-12-16 at 07 25 19" src="https://user-images.githubusercontent.com/12600222/146319778-fc57c0ea-03b1-423b-8434-2ec0cdd8b95c.png">

**Comment by ger19wmu** [comment]
My instance is a standalone running on a raspberry pi...that is really odd!   is there a way i can manually just install that repository?  i was checking it out here on git and didn't see install instructions.  Wondering if i can install it manually so the google notify install will skip over it maybe?

Thanks again for your assistance on this!

Edit:  tried again tonight.....same error!

**Comment by Paulf007** [comment]
Also having the same error. 
I have managed to install other node sop the connection is fine
