### ISSUE TITLE
Message to a speaker couple

### ISSUE THREAD

**Issue by totti1171** [orcema/node-red-google-notify#6]
If i couple 2 loudspeakers, it will not play the message.
(my nodered even crashes and restarts) :-(

**Comment by orcema** [comment]
could you please send some logs and specify:
- what kind of host/pc you are running node-red on
- do you run node-red standalone or as hass.io addon ?

**Comment by totti1171** [comment]
> could you please send some logs and specify:
> 
> * what kind of host/pc you are running node-red on

raspberry pie 4 8GB

> * do you run node-red standalone or as hass.io addon ?

raspberrymatic + redMatic addon

**Comment by totti1171** [comment]
I just tested it in a Docker container with Node Red 2..41 - the same result.
(Nodered crashes)

**Comment by totti1171** [comment]
new message -----
stdout
16:48:13
Queued messages [
stdout
16:48:13
  {
stdout
16:48:13
    devicePlaySettings: {
stdout
16:48:13
      msg: [Object],
stdout
16:48:13
      sourceNode: [GoogleNotify],
stdout
16:48:13
      ip: '192.168.178.158',
stdout
16:48:13
      playVolumeLevel: 0.8,
stdout
16:48:13
      playMessage: 'DIES ist ein Test',
stdout
16:48:13
      language: 'de',
stdout
16:48:13
      speakSlow: false,
stdout
16:48:13
      mediaServerUrl: 'http://192.168.178.41',
stdout
16:48:13
      mediaServerPort: '8098',
stdout
16:48:13
      cacheFolder: '/tmp'
stdout
16:48:13
    },
stdout
16:48:13
    callback: [Function (anonymous)]
stdout
16:48:13
  }
stdout
16:48:13
]
stdout
16:48:14
Queued messages [
stdout
16:48:14
  {
stdout
16:48:14
    devicePlaySettings: {
stdout
16:48:14
      msg: [Object],
stdout
16:48:14
      sourceNode: [GoogleNotify],
stdout
16:48:14
      ip: '192.168.178.158',
stdout
16:48:14
      playVolumeLevel: 0.8,
stdout
16:48:14
      playMessage: 'DIES ist ein Test',
stdout
16:48:14
      language: 'de',
stdout
16:48:14
      speakSlow: false,
stdout
16:48:14
      mediaServerUrl: 'http://192.168.178.41',
stdout
16:48:14
      mediaServerPort: '8098',
stdout
16:48:14
      cacheFolder: '/tmp'
stdout
16:48:14
    },
stdout
16:48:14
    callback: [Function (anonymous)]
stdout
16:48:14
  }
stdout
16:48:14
]
stdout
16:48:14
setting up mediaPlayUrl
stdout
16:48:14
preparing socket for connection to device
stdout
16:48:14
connecting with device
stdout
16:48:15
preparing player on device
stdout
16:48:15
2 Jan 16:48:15 - [red] Uncaught Exception:
stdout
16:48:15
2 Jan 16:48:15 - [error] ReferenceError: error is not defined
stdout
16:48:15
    at /data/node_modules/google-notify/google-notify.js:373:18
stdout
16:48:15
    at /data/node_modules/castv2-client/lib/senders/platform.js:95:20
stdout
16:48:15
    at /data/node_modules/castv2-client/lib/controllers/receiver.js:51:14
stdout
16:48:15
    at fn.onmessage (/data/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
stdout
16:48:15
    at fn.emit (events.js:412:35)
stdout
16:48:15
    at Channel.onmessage (/data/node_modules/castv2-client/lib/controllers/controller.js:16:10)

**Comment by orcema** [comment]
sorry but can't reproduce this error thus difficult for me to fix it
