### ISSUE TITLE
read msg.payload

### ISSUE THREAD

**Issue by Anto79-ops** [orcema/node-red-google-notify#8]
Hi great integration, makes my existing google speakers much more useful (it talks to me, instead of me just talking to it). This is not really an issue (more of a suggestion), but would be nice if the google-notify node can read msg.payload (or any custom identifier) instead of just msg.playMessage when the text box is empty.

**Comment by orcema** [comment]
This is actually implemented in version 1.4.7
[https://github.com/orcema/node-red-google-notify#:~:text=Comment-,1.4.7,-fix%20error%20and](https://github.com/orcema/node-red-google-notify#:~:text=Comment-,1.4.7,-fix%20error%20and)

If msg.playMessage is missing it will use the text in the msg.payload

**Comment by Anto79-ops** [comment]
oh good to know! thanks for this.

**Comment by Anto79-ops** [comment]
I'm using this in home assistant. Does it automatically update the plugin? How do I check the current version of that I installed on home assistant? Thanks
